class_name Constants

const BOID_SPEED = 150
const BOID_FLEEING_SPEED = 225
const PREDATOR_SPEED = 35
const PREDATOR_HUNTING_SPEED = 300

const SEPARATION_DISTANCE = 60
const ALIGNMENT_DISTANCE = 100
const COHESION_DISTANCE = 10

const PREDATOR_MAX_HUNGER = 5
const AVOID_PREDATOR_DISTANCE = 100
const BITING_DISTANCE = 10
