class_name Constants

const RESPAWN_AVERAGE_TIME = 2.0

const BOID_SPEED = 150.0
const BOID_FLEEING_SPEED = 225.0
const PREDATOR_SPEED = 35.0
const PREDATOR_HUNTING_SPEED = 300.0

const SEPARATION_DISTANCE = 60.0
const ALIGNMENT_DISTANCE = 100.0
const COHESION_DISTANCE = 10.0

const PREDATOR_MAX_HUNGER = 5.0
const AVOID_PREDATOR_DISTANCE = 100.0
const BITING_DISTANCE = 10.0
